// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

"use client";

//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Auth from "@/components/Protect";
import { useInitSession } from "@/store/useSession";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Your App",
//   description: "Your app description",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { getSession } = useInitSession((state) => state.actions);

  useEffect(() => {
    void getSession();
  }, []);

  // useEffect(() => {
  //   console.log("Calling getSession");
  //   getSession(true);
  // }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Exclude auth protection for the main page */}
        <Auth exclude={["/"]}>{children}</Auth>
      </body>
    </html>
  );
}
